# Generated by Django 5.1 on 2026-05-08 10:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('highway', models.CharField(blank=True, max_length=64, null=True)),
                ('ref', models.CharField(blank=True, max_length=64, null=True)),
                ('maxspeed', models.CharField(blank=True, max_length=32, null=True)),
                ('oneway', models.CharField(blank=True, max_length=8, null=True)),
                ('way', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planet_osm_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadNode',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'planet_osm_line_vertices_pgr',
                'managed': False,
            },
        ),
    ]
