# Generated by Django 5.1 on 2026-05-08 10:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('roadwork', 'Road work'), ('hazard', 'Hazard on road'), ('police', 'Police presence'), ('closure', 'Road closure'), ('traffic', 'Heavy traffic'), ('weather', 'Weather hazard')], max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('dismissals', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='incidents_is_acti_e46dd5_idx'), models.Index(fields=['incident_type'], name='incidents_inciden_994021_idx')],
            },
        ),
    ]
