# Generated by Django 5.1 on 2026-05-08 10:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amenity', models.CharField(blank=True, max_length=64, null=True)),
                ('tourism', models.CharField(blank=True, max_length=64, null=True)),
                ('shop', models.CharField(blank=True, max_length=64, null=True)),
                ('way', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'planet_osm_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeedCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('speed_limit', models.IntegerField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=32, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'speed_cameras',
                'ordering': ['speed_limit'],
            },
        ),
    ]
